[project]
name = "syft-rpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.9.2",
    "syft-core",
    "typing-extensions>=4.12.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
syft-core = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
