[project]
name = "syft-http-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "eelcovdw", email = "eelcovdw@gmail.com" }]
requires-python = ">=3.9"
dependencies = [
    "syft-core",
    "httpx>=0.28.1",
    "ormsgpack>=1.8.0",
    "loguru>=0.7.3",
    "watchdog>=6.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
syft-http-bridge = "syft_http_bridge.cli:cli"

[project.optional-dependencies]
cli = ["pyyaml>=6.0.2", "typer>=0.15.1"]
